version: "3.8"


volumes:
    cache:
    solutions:

    acme:
    certs:
    vhost:
    html:


services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy:1.3.1
        container_name: nginx-proxy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        environment:
            DHPARAM_SKIP: "true"
        volumes:
            - certs:/etc/nginx/certs:ro
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro

    acme-companion:
        image: nginxproxy/acme-companion:2.2.8
        container_name: nginx-proxy-acme
        restart: always
        environment:
            DEFAULT_EMAIL: no-reply@sreweek.ru
            NGINX_PROXY_CONTAINER: nginx-proxy
        volumes:
            - acme:/etc/acme.sh
            - certs:/etc/nginx/certs
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro

    manytask:
        image: manytask:build  # set SPECIFIC version you'll use
        container_name: manytask
        restart: always
        expose:
            - "5050"
        env_file: .env
        environment:
            VIRTUAL_HOST: manytask.sreweek.ru
            VIRTUAL_PORT: 5050
            LETSENCRYPT_HOST: manytask.sreweek.ru
        volumes:
            - cache:/cache
            - solutions:/solutions
